### PR TITLE
Amazonka Merge Request

### PR DESCRIPTION
**Pull request by misandrist**
Hey hey, again, **not to be merged yet** (especially since it's literally just a _README_), but a place to track what's going on with it. I plan on starting in on it today as soon as I've finished up some last touches on PKI.

Thanks!

### CODE REVIEW

**Comment by misandrist** [comment]
So as I was saying, Amazonka is fairly comprehensive. I've been working independently on just learning all of it's oddities and usages and things, and have quite a bit of ideas for it still. It might also be a good place to start working on more type-level resource management. I've got a pressing need for a working AWS setup/configuration engine (in addition to system config), so I may not make much progress here for a bit, but I'm definitely pushing forward.

**Comment by joeyh** [comment]
One concern I have with amazonka and propellor is it's a lot of
dependencies to add for those who don't need it. It may even be a lot of
dependencies for propellor running on individual AWS nodes, if those
instances don't need to use the APIs to provision others.

So it would be good to find a way to make the dependency only be added
in configurations that use it. Possibly a cabal build flag, possibly a
separate library from the core of propellor, etc.

-- 
see shy jo

**Comment by misandrist** [comment]
Oh yeah, definitely. One of the ideas I had was making a package that would include both, then do AWS setup, then spin up hosts using propellor. I'm definitely in a bit of a project where I could experiment with a lot of these ideas, too.

**Comment by joeyh** [comment]
Please submit changes to http://propellor.branchable.com/todo/ instead of using github pull requests, which are not part of my workflow. Just open a todo item there and link to a git repository containing your changes. Did you know, git is a distributed system? The git repository doesn't even need to be on github! Please send any complaints to Github; they don't allow turning off pull requests or redirecting them elsewhere.  -- A robot acting on behalf of Joey Hess

**Pull request closed without merging**
