### PR TITLE
FreeBSD Port of Propellor

### PR DESCRIPTION
**Pull request by misandrist**
I definitely don't want to merge this yet. This is just a placeholder for tracking the work I'm doing so far on it.

Thanks!

### CODE REVIEW

**Comment by joeyh** [comment]
Evan Cofsky wrote:
> I definitely don't want to merge this yet. This is just a placeholder for
> tracking the work I'm doing so far on it.

Wow, this is awesome!

Could you please make a post at http://propellor.branchable.com/todo/
when it's ready for merging?

Looking at what you have, I think you're very much on the right track.

I am a little bit puzzled by the change to buildFirst.

-- 
see shy jo

**Comment by misandrist** [comment]
Ok, yeah, so buildFirst. It's an interesting function, and my approach is definitely wrong for it. But the original version was checking the mtime of `propellor`, running the build, and then checking the mtime again. If the times matched it would continue with `next`, otherwise, it would run the build again.

On FreeBSD, the mtime was getting updated after each build, so it was just running the build over and over. For now, I've just bypassed that altogether, but I think it's also ignoring build errors now (and might have been before?). I don't know exactly what the right thing to do is.

What would be the downsides to just checking that the build succeeded before continuing, instead of checking the mtime?

**Comment by joeyh** [comment]
Evan Cofsky wrote:
> Ok, yeah, so buildFirst. It's an interesting function, and my approach is
> definitely wrong for it. But the original version was checking the mtime of
> propellor, running the build, and then checking the mtime again. If the times
> matched it would continue with next, otherwise, it would run the build again.
> 
> On FreeBSD, the mtime was getting updated after each build

Perhaps this has something to do with Propellor.Bootstrap.build's use of
cp -a to copy the binary into place? IIRC that may not work on BSD.

> What would be the downsides to just checking that the build succeeded before
> continuing, instead of checking the mtime?

buildPropellor throws an exception if the build fails. The purpose of
checking the mtime is not to detect build failure, but to detect when
ghc didn't need to do anything to update the build, and so left the
binary unchanged. In that case, the mtime is unchanged and so propellor
knows that the running version is up-to-date and it does not need to
re-exec itself.

-- 
see shy jo

**Comment by misandrist** [comment]
Oooooh, yeah, very tricky. And `cp -a` should copy the mtime, according to the man page, so I wonder if ghc was just relinking it every time, and then updating the mtime.

I just checked Bootstrap again, and it's using `cp -af`. I wonder if the `-f` on FreeBSD is causing the problem.

I'll dig in a bit more and see what I find out.

**Comment by misandrist** [comment]
Well that was easy:


    root@propellor:/usr/local/propellor # cabal build
    Building propellor-2.16.0...
    Preprocessing library propellor-2.16.0...
    In-place registering propellor-2.16.0...
    Preprocessing executable 'propellor' for propellor-2.16.0...
    Linking dist/build/propellor/propellor ...
    Preprocessing executable 'propellor-config' for propellor-2.16.0...
    Linking dist/build/propellor-config/propellor-config ...
    root@propellor:/usr/local/propellor # cabal --version
    cabal-install version 1.22.6.0
    using version 1.22.4.0 of the Cabal library
    root@propellor:/usr/local/propellor # cabal build
    Building propellor-2.16.0...
    Preprocessing library propellor-2.16.0...
    In-place registering propellor-2.16.0...
    Preprocessing executable 'propellor' for propellor-2.16.0...
    Linking dist/build/propellor/propellor ...
    Preprocessing executable 'propellor-config' for propellor-2.16.0...
    Linking dist/build/propellor-config/propellor-config ...
    root@propellor:/usr/local/propellor # 

Cabal is relinking it each time, which updates the mtime. I wonder if the sensible thing to do for now is just to always reexecute after building?

**Comment by misandrist** [comment]
Here we go:

http://haskell.1045720.n5.nabble.com/cabal-keeps-relinking-td5759549.html

It's a difference in the way `ar` behaves on FreeBSD vs Linux, I think.

**Comment by joeyh** [comment]
Evan Cofsky wrote:
> Oooooh, yeah, very tricky. And cp -a should copy the mtime, according to the
> man page, so I wonder if ghc was just relinking it every time, and then
> updating the mtime.

Seems quite possible it might do that. I'm feeling lucky that when I
cabal build repeatedly, stat reports the same mtime on linux.

-- 
see shy jo

**Comment by misandrist** [comment]
Ok, so, 8ef67de, it's definitely not ideal, but it might be a step in the right direction?

**Comment by joeyh** [comment]
Evan Cofsky wrote:
> Ok, so, 8ef67de, it's definitely not ideal, but it might be a step in the right
> direction?

It could keep the mtime check and use --continue-built as well, to avoid
looping if it relinks every time. I think that would be the best of both
worlds, and I'd cherry-pick such a commit over immediately.

-- 
see shy jo

**Comment by misandrist** [comment]
I think I understood what you meant with a2c766e. It now does the mtime check and calls next if it passes, otherwise it reruns propellor with the --check-built flag. I've tested it on FreeBSD at least, and it does work as expected there.

**Comment by misandrist** [comment]
As a bit of an aside, and most definitely not for this round of implementation, I was thinking that turning different "backends" for properties into a typeclass, and then having each Host parameterized over that as well might make a lot of this cleaner in the future. For now I think having the code paths explicitly different is definitely the right thing to get FreeBSD support, but at some point as we see what changes are caused by this effort, there might definitely be some clear-cut orthogonality we could lift into the type system. Something like

    data Host o = ...

where `o` is the operating system and the various properties can have "driver" functions based on which OS it is. And then additional type parameters could be added as we find other things that can be configured independently.

But yeah, for now, I'm definitely thinking the incremental approach is the right thing.

**Comment by joeyh** [comment]
Looking at a2c766e, I discovered that propellor was supposed to already
guard against repeated rebuilds, but the code was unclear and rotted.
I've fixed it up.

-- 
see shy jo

**Comment by joeyh** [comment]
I'd generally like to find ways to lift a lot of what's in Info to the
type level. Lifting the OS would avoid adding properties that are not
implemented for a host's OS; lifting eg port data and other exclusive
resources would allow for 
http://propellor.branchable.com/todo/type_level_port_conflict_detection/

-- 
see shy jo

**Comment by misandrist** [comment]
Ok, yeah, 6bb39d0 looks way clearer. I'll rebase in a bit and give it a try. In the mean time I'm running down the ZFS rabbit hole so I can run down the Poudriere rabbit hole and then maybe jails so I can start my package build vm...

**Comment by misandrist** [comment]
What do you think of the idea of having a Filesystems module and having the ZFS module I'm working on now living there? Sort of a step towards maybe a Filesystem typeclass that maybe could be a parameter on something. Like a mount point or something. Sorry, idle thoughts on a train ride.

**Comment by joeyh** [comment]
Evan Cofsky wrote:
> What do you think of the idea of having a Filesystems module and having the ZFS
> module I'm working on now living there? Sort of a step towards maybe a
> Filesystem typeclass that maybe could be a parameter on something. Like a mount
> point or something. Sorry, idle thoughts on a train ride.

There is already a Partition module that knows how to create many
filesystems.

-- 
see shy jo

**Comment by misandrist** [comment]
Sorry I've been out of touch. I was trying a lot of different things for ZFS support and eventually settled on something, at least. So now at least creating ZFS volumes is in, and that's 8274e64.

The next thing I do will be to rebase and see if I can merge in the new repeated build guard code.

Thanks!

**Comment by misandrist** [comment]
Sadly my first try at rebasing seems to have made the build loop return. I'll dig into it tomorrow.

Thanks again!

**Comment by misandrist** [comment]
Ok, it's definitely getting extra weird. The timestamps after building match now, so it's calling "next", but 1. they shouldn't match, and 2. it's definitely not taking the paths I've added debugging to. So I'm doing more digging.

**Comment by misandrist** [comment]
Ok, it's mostly working for creating ZFS volumes and setting properties. I still haven't dug into why the build loops even with the new CmdLine code.

**Comment by joeyh** [comment]
See if 4bbab3db9856b1c3fb4403add8b391179baf29c6 fixes your re-re-build problem.

-- 
see shy jo

**Comment by misandrist** [comment]
4bbab3d definitely fixes it. I've rebased against joeyh/master now, and so far all the FreeBSD bits I've been working on are working nicely.

**Comment by joeyh** [comment]
Reviewing.. 

.gitignore: The propellor file is created during regular use, so should
be ignored. Don't know why you removed it.

FreeBSD.md: Probably needs to move somewhere before/after I merge.
Move it to doc/FreeBSD.mdwn and it'll show up a
http://propellor.branchable.com/FreeBSD/
Or, freebsd documentation could be put in the Propellor.Property.FreeBSD
module using haccock.

config-freebsd.hs: I guess it's ok to have this as another sample
config, although I actually think it's rather cool that a single
config.hs could contain both linux and freebsd hosts..

src/Propellor/Bootstrap.hs: Changes to checkBinaryCommand don't make
sense to me.

src/Propellor/Bootstrap.hs: Some of the shell code in 
installGitCommand could be refactored.

Propellor/Property/Cron.hs: Not mergeable yet.

All the new modules you've added need license statements and Maintainer:
lines in their haddocks. Also, they need to be added to propellor.cabal

src/Propellor/Property/FreeBSD/Process.hs is not freebsd specific. 
Propellor.Property.Cmd covers more or less the same use case.

I wonder how specific src/Propellor/Property/FreeBSD/ZFS.hs
is to freebsd; linux has zfs too. This might want to move up one
directory.

There are a few whitespace changes unrelated to any code changes
(mostly removing trailing whitespace)
that I see in git diff, and at least the ones in src/Propellor/Spin.hs
conflict with changes I made to the same code today..

A few places don't comply with
http://propellor.branchable.com/coding_style/
Most of them involve using spaces for indentation while propellor's
source uses tabs. 

In src/Propellor/Types/OS.hs, there should be a space
before "FreeBSD FreeBSDRelease"

I guess that, at some point before I merge this, something will need to
be done about all the build warnings where pattern matching on
Distribution doesn't handle the FreeBSD case. It'd be an ok stopgap to add 

	FreeBSD _ -> error "FreeBSD not yet supported for this property"

-- 
see shy jo

**Comment by misandrist** [comment]
> .gitignore: The propellor file is created during regular use, so should
be ignored. Don't know why you removed it.

Oooh! I think what happened here was it was matching lots of things with "propellor" in the path, and not just the propellor file. It might be because I'm on a case-insensitive filesystem, too. I'll dig into it.

> FreeBSD.md: Probably needs to move somewhere before/after I merge.

I'll start by putting it under doc, and then as we (I) flesh out the Haddock more and more should appear there.

> config-freebsd.hs: I guess it's ok to have this as another sample
> config, although I actually think it's rather cool that a single
> config.hs could contain both linux and freebsd hosts..

I only did this for expediency of testing. I can merge it into the main config.hs sample.

> src/Propellor/Bootstrap.hs: Changes to checkBinaryCommand don't make
> sense to me.

Oh, hah! That's just some cruft from when I was flailing around trying to figure out where the looping was happening. I'll remove that.

> src/Propellor/Bootstrap.hs: Some of the shell code in
> installGitCommand could be refactored

I'll definitely take another pass at that too. It was really some of the first bits I did and I was definitely less comfortable with it then.

> Propellor/Property/Cron.hs: Not mergeable yet.

Definitely something I'll take care of.

> All the new modules you've added need license statements and Maintainer:
> lines in their haddocks. Also, they need to be added to propellor.cabal

I'll add these, too.

> src/Propellor/Property/FreeBSD/Process.hs is not freebsd specific.
> Propellor.Property.Cmd covers more or less the same use case.

Definitely the detritus of more flailing going on. I went through a lot of the Cmd code today to see how it all works and I'll definitely use that instead of my own.

> I wonder how specific src/Propellor/Property/FreeBSD/ZFS.hs
> is to freebsd; linux has zfs too. This might want to move up one
> directory.

It's literally the same userspace tools, so we can definitely move it up.

> A few places don't comply with
> http://propellor.branchable.com/coding_style/
> Most of them involve using spaces for indentation while propellor's
> source uses tabs.

I only just set up all the Emacs configuration you recommended this afternoon, and I'll definitely go through and fix up the coding style.

And I'll definitely see what we can do about the build warnings. I'm hoping to be slightly more clever than just having a runtime error but at the same time I've learned a lot about how clever I'm not so far.

Thank you so much for the comments so far!

**Comment by joeyh** [comment]
Evan Cofsky wrote:
>     .gitignore: The propellor file is created during regular use, so should
>     be ignored. Don't know why you removed it.
> 
> Oooh! I think what happened here was it was matching lots of things with
> "propellor" in the path, and not just the propellor file. It might be because
> I'm on a case-insensitive filesystem, too. I'll dig into it.

Ah, /propellor in .gitignore will make it ignore only the toplevel file.

-- 
see shy jo

**Comment by misandrist** [comment]
Ok, the latest rebase has everything above except the cron fix. I'm still trying to figure out how we can get the OS info from a Property (instead of from a Propellor).

**Comment by misandrist** [comment]
Also a bug in checking propellor jails I'll work on next.

**Comment by joeyh** [comment]
I've pulled this into my `wip` branch. I then beat on it for an hour, 
made several fixes, and some stylistic improvements. So you'll
probably want to do any further changes on top of my wip branch.

I've ready to merge wip to master if it looks good to you, once the few
remaining build warnings get cleaned up.

-- 
see shy jo

**Comment by misandrist** [comment]
The respin issue I've fixed (mostly by using the right check* function). I'll start rebasing on wip then. I'm off for a bit, but I'll do it when I get back.

Thanks!

**Comment by misandrist** [comment]
Ok, 14a208b has been rebased on your wip branch.

**Comment by misandrist** [comment]
Also, so, for the bigger picture, essentially getting Pkg, ZFS, and Poudriere running mean that it'll be possible to set up build servers for FreeBSD packages, like, for example, a Propellor FreeBSD package. Or internal packages for things I'm working on, too, of course :)

**Comment by misandrist** [comment]
Ok, I've merged with master and wip. Since we're both touching things up I'll stop rebasing.

**Comment by misandrist** [comment]
Hah! ensureProperty! of course!

**Comment by misandrist** [comment]
Ok so yes, I'm doing one last test spin of my FreeBSD config now, and then if it passes, I'm convinced we'll be in great shape for a merge.

**Comment by misandrist** [comment]
Yay! Thank you so much! Exciting times! 🎉

**Comment by joeyh** [comment]
Evan Cofsky wrote:
> Yay! Thank you so much! Exciting times! 🎉

Superfuntimes! Thank you..

-- 
see shy jo

**Comment by joeyh** [comment]
http://propellor.branchable.com/todo/type_level_OS_requirements/

-- 
see shy jo

**Pull request closed without merging**
